/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.View.jFrame;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.Collection;
import javax.swing.text.View;
import org.graphstream.ui.graphicGraph.GraphicElement;
import org.graphstream.ui.graphicGraph.GraphicGraph;
import org.graphstream.ui.swing_viewer.ViewPanel;
import org.graphstream.ui.view.Camera;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.view.util.MouseManager;
import org.graphstream.ui.view.util.ShortcutManager;
import sae.Models.algocoloration.AlgoColoration;

/**
 *
 * @author sacha
 */
public class GraphstreamFrame extends javax.swing.JFrame {
    private AlgoColoration algoColoration = new AlgoColoration();
    /**
     * Creates new form GraphstreamFrame
     */
    public GraphstreamFrame(String chemin) {
        initComponents();

        // Set layout manager for jPanel1
        jPanel1.setLayout(new BorderLayout());

        // Load graph data
        algoColoration.setFichier(chemin);
        try {
            algoColoration.charger_graphe();
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Get the graph from AlgoColoration
        org.graphstream.graph.Graph graph = algoColoration.minConflict().getGraph();

        // Create the Viewer
        Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewer.enableAutoLayout();

        // Create the ViewPanel and add it to jPanel1
        org.graphstream.ui.swingViewer.ViewPanel viewPanel = viewer.addDefaultView(false);
        jPanel1.add(viewPanel, BorderLayout.CENTER);
        

        // Refresh jPanel1
        jPanel1.revalidate();
        jPanel1.repaint();
        setJLabel();
    }
    
    private void setJLabel(){
        kmaxLabel.setText("Kmax : " + algoColoration.getKmax());
        nbNodeLabel.setText("Nombre de sommets : " + algoColoration.getNbSommet());
        nbEdgeLabel.setText("Nombre d'arrêtes : " + algoColoration.getGraph().getEdgeCount());
        chromaticNumberLabel.setText("Nombre chromatique : " +algoColoration.countChromaticcNumber( algoColoration.minConflict().getGraph()));
        conflictLabel.setText("Nombre de conflits : " + algoColoration.minConflict().getConflict());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kmaxLabel = new javax.swing.JLabel();
        nbNodeLabel = new javax.swing.JLabel();
        nbEdgeLabel = new javax.swing.JLabel();
        chromaticNumberLabel = new javax.swing.JLabel();
        conflictLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(221, 221, 221));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(221, 221, 221));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Information sur la coloration");

        kmaxLabel.setText("Kmax :  Loading");

        nbNodeLabel.setText("Nombre de sommets : Loading");

        nbEdgeLabel.setText("Nombre d'arrêtes : Loading");

        chromaticNumberLabel.setText("Nombre chromatique : Loading");

        conflictLabel.setText("Nombre de conflits : Loading");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nbNodeLabel)
                    .addComponent(kmaxLabel)
                    .addComponent(nbEdgeLabel)
                    .addComponent(chromaticNumberLabel)
                    .addComponent(conflictLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kmaxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nbNodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nbEdgeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chromaticNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conflictLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(235, 173, 59));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Charger un autre graphe");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chromaticNumberLabel;
    private javax.swing.JLabel conflictLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kmaxLabel;
    private javax.swing.JLabel nbEdgeLabel;
    private javax.swing.JLabel nbNodeLabel;
    // End of variables declaration//GEN-END:variables
}
