/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.View.jFrame;

import java.awt.Dimension;
import javax.swing.JFrame;
import sae.View.jPanel.BackgroundPanel;
import sae.View.jDialog.JInfosDialog;
import sae.View.jDialog.LoadAgraphDialog;

/**
 * Fenêtre de bienvenue de l'application FFRplane. Permet à l'utilisateur de
 * choisir entre différentes options, comme charger un graphe, démarrer
 * l'application ou afficher des informations à propos. Cette fenêtre s'affiche
 * lors du lancement de l'application. Elle contient également un menu Fichier
 * permettant d'ouvrir un graphe. La fenêtre est configurée pour s'adapter à la
 * taille de l'écran de l'utilisateur et utilise une mise en page graphique
 * élaborée.
 *
 * @author fillo
 */
public class WelcomeFrame extends javax.swing.JFrame {
    /**
     * Crée une nouvelle instance de WelcomeFrame. (constructeur) Initialise les
     * composants graphiques de la fenêtre, la positionne au centre de l'écran
     * et maximise sa taille.
     */
    public WelcomeFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(1000,600));
        setExtendedState(JFrame.MAXIMIZED_BOTH);// Mettre la fenêtre en plein écran
        setContentPane(panelContent);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("FFRplane - Welcome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelContent = new BackgroundPanel(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\background.png");
        labelTitle = new javax.swing.JLabel();
        panelOptions = new javax.swing.JPanel();
        jButtonLoad = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();

        panelContent.setEnabled(false);
        panelContent.setOpaque(false);
        panelContent.setLayout(new java.awt.GridBagLayout());

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 100)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("FFR’ PLANE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 70, 0);
        panelContent.add(labelTitle, gridBagConstraints);

        panelOptions.setOpaque(false);
        panelOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        jButtonLoad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonLoad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoad.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\loadIcon.png"));
        jButtonLoad.setText("Charger un graphe");
        jButtonLoad.setBorder(null);
        jButtonLoad.setContentAreaFilled(false);
        jButtonLoad.setFocusPainted(false);
        jButtonLoad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLoad.setIconTextGap(20);
        jButtonLoad.setPreferredSize(new java.awt.Dimension(145, 180));
        jButtonLoad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonLoad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });
        panelOptions.add(jButtonLoad);

        jButtonStart.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonStart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStart.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\startIcon.png"));
        jButtonStart.setText("Charger l'espace aérien");
        jButtonStart.setBorder(null);
        jButtonStart.setContentAreaFilled(false);
        jButtonStart.setFocusPainted(false);
        jButtonStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStart.setIconTextGap(10);
        jButtonStart.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        panelOptions.add(jButtonStart);

        jButtonAbout.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAbout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAbout.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\aboutIcon.png"));
        jButtonAbout.setText("A propos");
        jButtonAbout.setBorder(null);
        jButtonAbout.setContentAreaFilled(false);
        jButtonAbout.setFocusPainted(false);
        jButtonAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbout.setIconTextGap(10);
        jButtonAbout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });
        panelOptions.add(jButtonAbout);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        panelContent.add(panelOptions, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gère les actions déclenchées par les événements associés aux boutons de
     * la fenêtre WelcomeFrame.
     */
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        MainFrame mainf = new MainFrame();
        mainf.setVisible(true);
    }//GEN-LAST:event_jButtonStartActionPerformed

    /**
     * Affiche une fenêtre modale JInfosDialog lorsque le bouton "À propos" est
     * cliqué. Cette fenêtre fournit des informations sur l'application.
     */
    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
        JInfosDialog infosD = new JInfosDialog(this, true);
        infosD.setLocationRelativeTo(this);
        infosD.setVisible(true);
    }//GEN-LAST:event_jButtonAboutActionPerformed

    /**
     * Affiche une fenêtre modale LoadAgraphDialog lorsque le bouton "Charger"
     * est cliqué. Cette fenêtre permet à l'utilisateur de charger un graphe.
     */
    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        LoadAgraphDialog loadD = new LoadAgraphDialog(this, true);
        loadD.setLocationRelativeTo(this);
        loadD.setVisible(true);
    }//GEN-LAST:event_jButtonLoadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelOptions;
    // End of variables declaration//GEN-END:variables
}    
