package sae.view.jFrame;

import java.awt.Dimension;
import javax.swing.*;

import sae.utils.*;
import sae.view.jPanel.*;
import sae.view.jDialog.*;

/**
 * Fenêtre de bienvenue de l'application FFRplane. Permet à l'utilisateur de
 * choisir entre différentes options, comme charger un graphe, démarrer
 * l'application ou afficher des informations à propos. Cette fenêtre s'affiche
 * lors du lancement de l'application. Elle contient également un menu Fichier
 * permettant d'ouvrir un graphe. La fenêtre est configurée pour s'adapter à la
 * taille de l'écran de l'utilisateur et utilise une mise en page graphique
 * élaborée.
 *
 * @author fillo
 * @author mathe
 */
public class WelcomeFrame extends javax.swing.JFrame {
    private final String backgroundImagePath = System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\background.png";
    private final ImageIcon iconLoadGraph = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\refresh2.png");
    private final ImageIcon iconLoadAirspace = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\startIcon.png");
    private final ImageIcon iconAbout = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\aboutIcon.png");
    private final IconUtil iconU = new IconUtil();
    
    /**
     * Crée une nouvelle instance de WelcomeFrame. (constructeur) Initialise les
     * composants graphiques de la fenêtre, la positionne au centre de l'écran
     * et maximise sa taille.
     */
    public WelcomeFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(1000,600));
        setExtendedState(JFrame.MAXIMIZED_BOTH);// Mettre la fenêtre en plein écran
        setContentPane(panelContent);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("FFRplane - Welcome");
        iconU.setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelContent = new BackgroundPanel(backgroundImagePath);
        labelTitle = new javax.swing.JLabel();
        panelOptions = new javax.swing.JPanel();
        buttonLoadGraph = new javax.swing.JButton();
        buttonLoadAirspace = new javax.swing.JButton();
        buttonAbout = new javax.swing.JButton();

        panelContent.setEnabled(false);
        panelContent.setOpaque(false);
        panelContent.setLayout(new java.awt.GridBagLayout());

        labelTitle.setBackground(new java.awt.Color(255, 255, 255));
        labelTitle.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 100)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("FFR’ PLANE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 70, 0);
        panelContent.add(labelTitle, gridBagConstraints);

        panelOptions.setOpaque(false);
        panelOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        buttonLoadGraph.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLoadGraph.setForeground(new java.awt.Color(255, 255, 255));
        buttonLoadGraph.setIcon(iconLoadGraph);
        buttonLoadGraph.setText("Charger un graphe");
        buttonLoadGraph.setBorder(null);
        buttonLoadGraph.setContentAreaFilled(false);
        buttonLoadGraph.setFocusPainted(false);
        buttonLoadGraph.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLoadGraph.setIconTextGap(20);
        buttonLoadGraph.setPreferredSize(new java.awt.Dimension(145, 180));
        buttonLoadGraph.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        buttonLoadGraph.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonLoadGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadGraphActionPerformed(evt);
            }
        });
        panelOptions.add(buttonLoadGraph);

        buttonLoadAirspace.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonLoadAirspace.setForeground(new java.awt.Color(255, 255, 255));
        buttonLoadAirspace.setIcon(iconLoadAirspace);
        buttonLoadAirspace.setText("Charger l'espace aérien");
        buttonLoadAirspace.setBorder(null);
        buttonLoadAirspace.setContentAreaFilled(false);
        buttonLoadAirspace.setFocusPainted(false);
        buttonLoadAirspace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLoadAirspace.setIconTextGap(10);
        buttonLoadAirspace.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        buttonLoadAirspace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonLoadAirspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadAirspaceActionPerformed(evt);
            }
        });
        panelOptions.add(buttonLoadAirspace);

        buttonAbout.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        buttonAbout.setForeground(new java.awt.Color(255, 255, 255));
        buttonAbout.setIcon(iconAbout);
        buttonAbout.setText("A propos");
        buttonAbout.setBorder(null);
        buttonAbout.setContentAreaFilled(false);
        buttonAbout.setFocusPainted(false);
        buttonAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAbout.setIconTextGap(10);
        buttonAbout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        buttonAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAboutActionPerformed(evt);
            }
        });
        panelOptions.add(buttonAbout);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        panelContent.add(panelOptions, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /* ••••••••••••• LISTENERS ••••••••••••• */
    
    
    /**
     * Gère les actions déclenchées par les événements associés aux boutons de
     * la fenêtre WelcomeFrame.
     */
    private void buttonLoadAirspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadAirspaceActionPerformed
        LoadAirspaceDialog loadD = new LoadAirspaceDialog(this, true);
        loadD.setLocationRelativeTo(this);
        loadD.setVisible(true);
    }//GEN-LAST:event_buttonLoadAirspaceActionPerformed

    
    /**
     * Affiche une fenêtre modale JInfosDialog lorsque le bouton "À propos" est
     * cliqué. Cette fenêtre fournit des informations sur l'application.
     */
    private void buttonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAboutActionPerformed
        JInfosDialog infosD = new JInfosDialog(this, true);
        infosD.setLocationRelativeTo(this);
        infosD.setVisible(true);
    }//GEN-LAST:event_buttonAboutActionPerformed

    
    /**
     * Affiche une fenêtre modale LoadAgraphDialog lorsque le bouton "Charger"
     * est cliqué. Cette fenêtre permet à l'utilisateur de charger un graphe.
     */
    private void buttonLoadGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadGraphActionPerformed
        LoadGraphDialog loadD = new LoadGraphDialog(this, true);
        loadD.setLocationRelativeTo(this);
        loadD.setVisible(true);
    }//GEN-LAST:event_buttonLoadGraphActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbout;
    private javax.swing.JButton buttonLoadAirspace;
    private javax.swing.JButton buttonLoadGraph;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelOptions;
    // End of variables declaration//GEN-END:variables
}    
