/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sae.View.jDialog;

import sae.Utils.IconUtil;

/**
 * Cette classe correspond à la dialog comportant tout les éléments liés aux
 * couleurs et permet l'édition et la modification de tout ces éléments
 *
 * @author fillo
 */
public class ColorationsDialog extends javax.swing.JDialog {

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    /**
     * Constructeur de la classe ColorationsDialog.
     *
     * @param parent La fenêtre parente de ce dialogue.
     * @param modal Indique si le dialogue est modal ou non.
     */
    public ColorationsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();
        iconU.setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditableItemsPanel = new javax.swing.JPanel();
        KmaxLabel = new javax.swing.JLabel();
        KmaxSpinner = new javax.swing.JSpinner();
        MinLabel = new javax.swing.JLabel();
        MinjSpinner = new javax.swing.JSpinner();
        actualHourjLabel = new javax.swing.JLabel();
        actualHourjSpinner1 = new javax.swing.JSpinner();
        TitlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ChoicesPanel = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FFRplane - coloration settings");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KmaxLabel.setText("kmax (niveau de vols) :");

        MinLabel.setText("marge de sécurité (en min) : ");

        MinjSpinner.setValue(15);

        actualHourjLabel.setText("éditer heure actuelle (HH.MM) : ");

        actualHourjSpinner1.setValue(15);

        javax.swing.GroupLayout EditableItemsPanelLayout = new javax.swing.GroupLayout(EditableItemsPanel);
        EditableItemsPanel.setLayout(EditableItemsPanelLayout);
        EditableItemsPanelLayout.setHorizontalGroup(
            EditableItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditableItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditableItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KmaxLabel)
                    .addComponent(MinLabel)
                    .addComponent(actualHourjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(EditableItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KmaxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualHourjSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        EditableItemsPanelLayout.setVerticalGroup(
            EditableItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditableItemsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditableItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KmaxLabel)
                    .addComponent(KmaxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditableItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MinLabel)
                    .addComponent(MinjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditableItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualHourjLabel)
                    .addComponent(actualHourjSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(EditableItemsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 360, -1));

        TitlePanel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ici vous pouvez modifier les paramètres de colorations");
        TitlePanel.add(jLabel1);

        getContentPane().add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        ChoicesPanel.setMaximumSize(new java.awt.Dimension(360, 80));
        ChoicesPanel.setMinimumSize(new java.awt.Dimension(360, 80));
        ChoicesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        CancelButton.setBackground(new java.awt.Color(235, 173, 59));
        CancelButton.setForeground(new java.awt.Color(0, 0, 0));
        CancelButton.setText("Annuler");
        CancelButton.setFocusPainted(false);
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 25));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 25));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        ChoicesPanel.add(CancelButton);

        OkButton.setBackground(new java.awt.Color(235, 173, 59));
        OkButton.setForeground(new java.awt.Color(0, 0, 0));
        OkButton.setText("Ok");
        OkButton.setFocusPainted(false);
        OkButton.setMaximumSize(new java.awt.Dimension(100, 25));
        OkButton.setMinimumSize(new java.awt.Dimension(100, 25));
        OkButton.setPreferredSize(new java.awt.Dimension(100, 25));
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        ChoicesPanel.add(OkButton);

        getContentPane().add(ChoicesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        System.out.println("ok");
    }//GEN-LAST:event_OkButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel ChoicesPanel;
    private javax.swing.JPanel EditableItemsPanel;
    private javax.swing.JLabel KmaxLabel;
    private javax.swing.JSpinner KmaxSpinner;
    private javax.swing.JLabel MinLabel;
    private javax.swing.JSpinner MinjSpinner;
    private javax.swing.JButton OkButton;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel actualHourjLabel;
    private javax.swing.JSpinner actualHourjSpinner1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
