package sae.view.jDialog.functionsDialog;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

import sae.utils.IconUtil;
import sae.view.jFrame.MainFrame;


/**
 * Cette classe représente une boîte de dialogue permettant de choisir parmi
 * plusieurs fonctions d'affinage pour les vols.
 * Elle étend javax.swing.JDialog.
 *
 * L'utilisateur peut choisir parmi les options suivantes :
 * - Charger le Graph de coloration
 * - Afficher les vols à une hauteur donnée
 * - Afficher les vols dans un intervalle horaire donné
 * - Afficher les vols partant / arrivant d'un aéroport donné
 *
 * Lorsque l'option "Ok" est sélectionnée, la boîte de dialogue se ferme et
 * affiche la fenêtre correspondante à l'option choisie.
 * Elle utilise également l'instance de IconUtil pour configurer les icônes des
 * composants graphiques.
 *
 * @author mathe
 */
public class FunctionChooserDialog extends javax.swing.JDialog {
    
    private final DefaultComboBoxModel modelComboBox = new DefaultComboBoxModel<>(new String[]{
        "Charger le Graph de coloration",
        "Afficher les vols à une hauteur donnée",
        "Afficher les vols dans un intervalle horaire donné", 
        "Afficher les vols partant / arrivant d'un aéroport donné"
    });

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    /**
     * Constructeur de la classe FunctionChooserDialog.
     *
     * @param parent Le frame parent de la boîte de dialogue.
     * @param modal Un booléen indiquant si la boîte de dialogue est modale ou non.
     */
    public FunctionChooserDialog(MainFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iconU.setIcon(this);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBottomPanel = new javax.swing.JPanel();
        jCancelButton = new javax.swing.JButton();
        jOkayButton = new javax.swing.JButton();
        jTopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxFonctions = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FFRplane - Fonctions ");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 230));

        jCancelButton.setBackground(new java.awt.Color(235, 173, 59));
        jCancelButton.setForeground(new java.awt.Color(0, 0, 0));
        jCancelButton.setText("Annuler");
        jCancelButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });
        jBottomPanel.add(jCancelButton);

        jOkayButton.setBackground(new java.awt.Color(235, 173, 59));
        jOkayButton.setForeground(new java.awt.Color(0, 0, 0));
        jOkayButton.setText("Ok");
        jOkayButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jOkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkayButtonActionPerformed(evt);
            }
        });
        jBottomPanel.add(jOkayButton);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez une fonction d'affinage");

        jComboBoxFonctions.setModel(modelComboBox);
        jComboBoxFonctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFonctionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTopPanelLayout = new javax.swing.GroupLayout(jTopPanel);
        jTopPanel.setLayout(jTopPanelLayout);
        jTopPanelLayout.setHorizontalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBoxFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jTopPanelLayout.setVerticalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jComboBoxFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /* ••••••••••••• LISTENERS ••••••••••••• */
    
    
    /**
     * Méthode appelée lorsqu'un événement d'action se produit sur jComboBoxFonctions.
     * Cette méthode est actuellement vide et n'effectue aucune action.
     *
     * @param evt L'événement d'action associé à l'appel de cette méthode.
     */
    private void jComboBoxFonctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFonctionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFonctionsActionPerformed

    
    /**
     * Méthode appelée lorsqu'un événement d'action se produit sur jCancelButton.
     * Cette méthode ferme la boîte de dialogue actuelle.
     *
     * @param evt L'événement d'action associé à l'appel de cette méthode.
     */
    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    
    /**
     * Méthode appelée lorsqu'un événement d'action se produit sur jOkayButton.
     * Cette méthode effectue différentes actions en fonction de l'option
     * sélectionnée dans jComboBoxFonctions, comme l'affichage de différentes
     * boîtes de dialogue.
     *
     * @param evt L'événement d'action associé à l'appel de cette méthode.
     */
    private void jOkayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkayButtonActionPerformed
        if (modelComboBox.getSelectedItem().equals("Charger le Graph de coloration")){
            dispose();
            ChooseColorationAlgorithmDialog chooseAlgorithm = new ChooseColorationAlgorithmDialog((JFrame) this.getParent(), true);
            chooseAlgorithm.setVisible(true);
        } else if (modelComboBox.getSelectedItem().equals("Afficher les vols à une hauteur donnée")){
            dispose();
            ChooseHeightLevelDialog chooseHeightLevelDialog = new ChooseHeightLevelDialog((JFrame)this.getParent(),true);
            chooseHeightLevelDialog.setVisible(true);
        } else if (modelComboBox.getSelectedItem().equals("Afficher les vols dans un intervalle horaire donné")) {
            dispose();
            ChooseTimeRangeDialog chooseTimeRangeDialog = new ChooseTimeRangeDialog((JFrame)this.getParent(), true);
            chooseTimeRangeDialog.setVisible(true);  
        } else if (modelComboBox.getSelectedItem().equals("Afficher les vols partant / arrivant d'un aéroport donné")){
            dispose();
            ChooseAirportDialog chooseAirportDialog = new ChooseAirportDialog((JFrame)this.getParent(), true);
            chooseAirportDialog.setVisible(true);
        }
    }//GEN-LAST:event_jOkayButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBottomPanel;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox<String> jComboBoxFonctions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jOkayButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables
}
