/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sae.view.jDialog;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import sae.View.jDialog.ChooseAlgorithmDialog;
import sae.utils.IconUtil;

/**
 * Cette classe représente une boîte de dialogue pour les fonctions de
 * l'application. Elle étend la classe javax.swing.JDialog.
 *
 * @author fillo
 */
public class FonctionsDialog extends javax.swing.JDialog {
    private final DefaultComboBoxModel modelComboBox = new DefaultComboBoxModel<>(new String[]{
        "Afficher les vols dans un intervalle donné", 
        "Afficher les vols partant / arrivant d'un aéroport donné", 
        "Afficher les vols à une hauteur donnée", 
        "Colorier le graphe avec un algorithme de coloration",
        "NOT CONFIGURED"
    });

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    
    /**
     * Constructeur de la classe FonctionsDialog.
     *
     * @param parent Le frame parent de la boîte de dialogue.
     * @param modal Un booléen indiquant si la boîte de dialogue est modale ou
     * non.
     */
    public FonctionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iconU.setIcon(this);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBottomPanel = new javax.swing.JPanel();
        jCancelButton = new javax.swing.JButton();
        jOkayButton = new javax.swing.JButton();
        jTopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxFonctions = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FFRplane - Fonctions ");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 230));

        jCancelButton.setBackground(new java.awt.Color(235, 173, 59));
        jCancelButton.setForeground(new java.awt.Color(0, 0, 0));
        jCancelButton.setText("Annuler");
        jCancelButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });
        jBottomPanel.add(jCancelButton);

        jOkayButton.setBackground(new java.awt.Color(235, 173, 59));
        jOkayButton.setForeground(new java.awt.Color(0, 0, 0));
        jOkayButton.setText("Ok");
        jOkayButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jOkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkayButtonActionPerformed(evt);
            }
        });
        jBottomPanel.add(jOkayButton);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez une fonction d'affinage");

        jComboBoxFonctions.setModel(modelComboBox);
        jComboBoxFonctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFonctionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTopPanelLayout = new javax.swing.GroupLayout(jTopPanel);
        jTopPanel.setLayout(jTopPanelLayout);
        jTopPanelLayout.setHorizontalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBoxFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jTopPanelLayout.setVerticalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jComboBoxFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jComboBoxFonctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFonctionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFonctionsActionPerformed

    
    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    
    private void jOkayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkayButtonActionPerformed
        if (modelComboBox.getSelectedItem().equals("Colorier le graphe avec un algorithme de coloration")){
            this.dispose();
            ChooseAlgorithmDialog chooseAlgorithm = new ChooseAlgorithmDialog((JFrame) this.getParent(), true);
            chooseAlgorithm.setVisible(true);
        }
    }//GEN-LAST:event_jOkayButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBottomPanel;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox<String> jComboBoxFonctions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jOkayButton;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables
}
