/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sae.view.jDialog;

import sae.utils.IconUtil;

/**
 * Cette classe représente une boîte de dialogue pour les fonctions de
 * l'application. Elle étend la classe javax.swing.JDialog.
 *
 * @author fillo
 */
public class FonctionsDialog extends javax.swing.JDialog {

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    /**
     * Constructeur de la classe FonctionsDialog.
     *
     * @param parent Le frame parent de la boîte de dialogue.
     * @param modal Un booléen indiquant si la boîte de dialogue est modale ou
     * non.
     */
    public FonctionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iconU.setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBottomPanel = new javax.swing.JPanel();
        jCancelButton = new javax.swing.JButton();
        jOkayButton = new javax.swing.JButton();
        jTopPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxFonctions = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FFRplane - Fonctions ");

        jBottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        jCancelButton.setBackground(new java.awt.Color(235, 173, 59));
        jCancelButton.setForeground(new java.awt.Color(0, 0, 0));
        jCancelButton.setText("Annuler");
        jCancelButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jCancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });
        jBottomPanel.add(jCancelButton);

        jOkayButton.setBackground(new java.awt.Color(235, 173, 59));
        jOkayButton.setForeground(new java.awt.Color(0, 0, 0));
        jOkayButton.setText("Ok");
        jOkayButton.setMaximumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setMinimumSize(new java.awt.Dimension(100, 25));
        jOkayButton.setPreferredSize(new java.awt.Dimension(100, 25));
        jOkayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkayButtonActionPerformed(evt);
            }
        });
        jBottomPanel.add(jOkayButton);

        getContentPane().add(jBottomPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Tableau de bord des fonctions :");

        jComboBoxFonctions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afficher tous les vols en cours à une heure donnée", "Sélectionner un aéroport et visualiser les niveaux de chaque vol", "Sélectionner un niveau et afficher tous les vols pour ce niveau", "Colorier en fonction de ...(DSATUR, WP...)" }));
        jComboBoxFonctions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFonctionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTopPanelLayout = new javax.swing.GroupLayout(jTopPanel);
        jTopPanel.setLayout(jTopPanelLayout);
        jTopPanelLayout.setHorizontalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopPanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxFonctions, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTopPanelLayout.setVerticalGroup(
            jTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxFonctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jTopPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxFonctionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFonctionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFonctionsActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jOkayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOkayButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBottomPanel;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JComboBox<String> jComboBoxFonctions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jOkayButton;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables
}
