package sae.view.jDialog;

import sae.utils.IconUtil;

/**
 * Cette classe représente une boîte de dialogue de chargement de graphique.
 * Elle étend la classe javax.swing.JDialog.
 * 
 * @author fillo
 */
public class JInfosDialog extends javax.swing.JDialog {

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    /**
     * Creates new form JInfosDialog
     */
    public JInfosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();
        iconU.setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        infosLabel1 = new javax.swing.JLabel();
        infosLabel2 = new javax.swing.JLabel();
        infosLabel3 = new javax.swing.JLabel();
        copyrightsLabel = new javax.swing.JLabel();
        DeveloppersLabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FFRplane - About the app");
        setResizable(false);

        infosLabel1.setText("Cette application développé en Java Swing à pour but de gérer le parc aérien");

        infosLabel2.setText(" français et d'y repérer les vols qui vont rentrer en collision pour corriger leurs");

        infosLabel3.setText(" niveau de vols,cette application utilise la théorie des gars et de la coloration.");

        copyrightsLabel.setText("© 2024 Tous droits réservés");

        DeveloppersLabel.setText("Développé avec ♥ par Matheo FLORES, Sacha ROUX, Florian FILLOUX.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infosLabel1)
                            .addComponent(infosLabel2)
                            .addComponent(infosLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(copyrightsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DeveloppersLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infosLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infosLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infosLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(DeveloppersLabel)
                .addGap(21, 21, 21)
                .addComponent(copyrightsLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeveloppersLabel;
    private javax.swing.JLabel copyrightsLabel;
    private javax.swing.JLabel infosLabel1;
    private javax.swing.JLabel infosLabel2;
    private javax.swing.JLabel infosLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
