package sae.view.jDialog;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

import sae.exceptions.DataMismatchException;
import sae.exceptions.FileFormatException;
import sae.models.airports.AirportsCatalog;
import sae.models.flights.FlightsCatalog;
import sae.models.toolbox.ToolBox;
import sae.utils.IconUtil;
import sae.utils.Settings;
import sae.view.jFileChooser.OpenFileChooser;
import sae.view.jFrame.MainFrame;


/**
 * Cette classe permet de charger un espace aérien.
 * Elle étend la classe javax.swing.JDialog.
 *
 * @author fillo
 * @author mathe
 */
public class LoadAirspaceDialog extends javax.swing.JDialog {

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    
    /**
     * Crée une nouvelle instance de la LoadAirspaceDialog qui permet de spécifier 
     * les liens des fichiers qui crééront la MainFrame
     *
     * @param parent La fenêtre parente de la LoadAirspaceDialog.
     * @param modal Spécifie si la LoadAirspaceDialog doit être modale ou non.
     */
    public LoadAirspaceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();
        iconU.setIcon(this);
        this.setResizable(false);
        if(Settings.getAirportsFilePath()!=null) airportsFileTextField.setText(Settings.getAirportsFilePath());
        if(Settings.getFlightsFilePath()!=null) flightsFileTextField.setText(Settings.getFlightsFilePath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        ChoicesPanel = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();
        firstFileLabel = new javax.swing.JLabel();
        secondFileLabel = new javax.swing.JLabel();
        buttonChooseAirportFile = new javax.swing.JButton();
        buttonChooseFlightsFile = new javax.swing.JButton();
        airportsFileTextField = new javax.swing.JTextField();
        flightsFileTextField = new javax.swing.JTextField();
        labelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Charger un espace aérien");
        setResizable(false);

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Sélectionnez les fichiers suivants");

        ChoicesPanel.setMaximumSize(new java.awt.Dimension(360, 80));
        ChoicesPanel.setMinimumSize(new java.awt.Dimension(360, 80));

        CancelButton.setBackground(new java.awt.Color(235, 173, 59));
        CancelButton.setForeground(new java.awt.Color(0, 0, 0));
        CancelButton.setText("Annuler");
        CancelButton.setFocusPainted(false);
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 25));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 25));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        ChoicesPanel.add(CancelButton);

        OkButton.setBackground(new java.awt.Color(235, 173, 59));
        OkButton.setForeground(new java.awt.Color(0, 0, 0));
        OkButton.setText("Ok");
        OkButton.setFocusPainted(false);
        OkButton.setMaximumSize(new java.awt.Dimension(100, 25));
        OkButton.setMinimumSize(new java.awt.Dimension(100, 25));
        OkButton.setPreferredSize(new java.awt.Dimension(100, 25));
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        ChoicesPanel.add(OkButton);

        firstFileLabel.setText("Choisissez votre fichier d'aeroports :");

        secondFileLabel.setText("Choisissez votre fichier de vol-test :");

        buttonChooseAirportFile.setBackground(new java.awt.Color(235, 173, 59));
        buttonChooseAirportFile.setForeground(new java.awt.Color(0, 0, 0));
        buttonChooseAirportFile.setText("Ouvrir"); // NOI18N
        buttonChooseAirportFile.setFocusPainted(false);
        buttonChooseAirportFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseAirportFileActionPerformed(evt);
            }
        });

        buttonChooseFlightsFile.setBackground(new java.awt.Color(235, 173, 59));
        buttonChooseFlightsFile.setForeground(new java.awt.Color(0, 0, 0));
        buttonChooseFlightsFile.setText("Ouvrir");
        buttonChooseFlightsFile.setFocusPainted(false);
        buttonChooseFlightsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseFlightsFileActionPerformed(evt);
            }
        });

        flightsFileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightsFileTextFieldActionPerformed(evt);
            }
        });

        labelError.setForeground(new java.awt.Color(255, 51, 51));
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(firstFileLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChoicesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                                .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(secondFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airportsFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flightsFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonChooseAirportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonChooseFlightsFile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleLabel)
                .addGap(30, 30, 30)
                .addComponent(firstFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airportsFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonChooseAirportFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(secondFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChooseFlightsFile)
                    .addComponent(flightsFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChoicesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /* ••••••••••••• LISTENERS ••••••••••••• */
    
    
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    
    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        try {
            // <* Cette partie ne sert qu'à déclancher les exceptions
            AirportsCatalog temp = new AirportsCatalog();
            ToolBox.fillAirportsCatalog(airportsFileTextField.getText(), temp);
            ToolBox.fillFlightsCatalog(airportsFileTextField.getText(),flightsFileTextField.getText(), new FlightsCatalog(), temp);
            // *>
            
            Settings.setAirportsFilePath(airportsFileTextField.getText());
            Settings.setFlightsFilePath(flightsFileTextField.getText());
            Settings.setRefiningColor(0);
            dispose();
            SwingUtilities.getWindowAncestor(this).dispose();
            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);
            
        } catch(FileNotFoundException e){
            labelError.setText("L'un des chemin d'accès est introuvable !");
        } catch(FileFormatException e) {
            labelError.setText(e.getMessage());
        } catch (DataMismatchException e){
            labelError.setText(e.getMessage());
        }
    }//GEN-LAST:event_OkButtonActionPerformed

    
    private void buttonChooseAirportFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseAirportFileActionPerformed
        JFileChooser fileChooser = new OpenFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir") + "\\src\\main\\java\\data\\"));
        
        int result = fileChooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) {
            airportsFileTextField.setText(fileChooser.getSelectedFile().getPath());
        } else if(result == JFileChooser.CANCEL_OPTION) {}
    }//GEN-LAST:event_buttonChooseAirportFileActionPerformed

    
    private void buttonChooseFlightsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseFlightsFileActionPerformed
        JFileChooser fileChooser = new OpenFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir") + "\\src\\main\\java\\data\\"));
        
        int result = fileChooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) {
            flightsFileTextField.setText(fileChooser.getSelectedFile().getPath());
        } else if(result == JFileChooser.CANCEL_OPTION) {}
    }//GEN-LAST:event_buttonChooseFlightsFileActionPerformed

    
    private void flightsFileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightsFileTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightsFileTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel ChoicesPanel;
    private javax.swing.JButton OkButton;
    private javax.swing.JTextField airportsFileTextField;
    private javax.swing.JButton buttonChooseAirportFile;
    private javax.swing.JButton buttonChooseFlightsFile;
    private javax.swing.JLabel firstFileLabel;
    private javax.swing.JTextField flightsFileTextField;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel secondFileLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
