/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sae.View.jDialog;

import sae.Utils.IconUtil;

/**
 * Cette classe représente une boîte de dialogue de chargement de graphique.
 * Elle étend la classe javax.swing.JDialog.
 *
 * @author fillo
 */
public class LoadAgraphDialog extends javax.swing.JDialog {

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    /**
     * Crée une nouvelle instance de la boîte de dialogue de chargement de
     * graphique qui permet de spécifier les liens des fichiers qui crééront le
     * graphe
     *
     * @param parent La fenêtre parente de la boîte de dialogue.
     * @param modal Spécifie si la boîte de dialogue doit être modale ou non.
     */
    public LoadAgraphDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();
        iconU.setIcon(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        ChoicesPanel = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();
        firstFileLabel = new javax.swing.JLabel();
        secondFileLabel = new javax.swing.JLabel();
        choiceFileButton1 = new javax.swing.JButton();
        choiceFileButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("load a graph");
        setResizable(false);

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Sélectionnez votre fichier pour charger votre graphique");

        ChoicesPanel.setMaximumSize(new java.awt.Dimension(360, 80));
        ChoicesPanel.setMinimumSize(new java.awt.Dimension(360, 80));
        ChoicesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        CancelButton.setBackground(new java.awt.Color(235, 173, 59));
        CancelButton.setForeground(new java.awt.Color(0, 0, 0));
        CancelButton.setText("Annuler");
        CancelButton.setFocusPainted(false);
        CancelButton.setMaximumSize(new java.awt.Dimension(100, 25));
        CancelButton.setMinimumSize(new java.awt.Dimension(100, 25));
        CancelButton.setPreferredSize(new java.awt.Dimension(100, 25));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        ChoicesPanel.add(CancelButton);

        OkButton.setBackground(new java.awt.Color(235, 173, 59));
        OkButton.setForeground(new java.awt.Color(0, 0, 0));
        OkButton.setText("Ok");
        OkButton.setFocusPainted(false);
        OkButton.setMaximumSize(new java.awt.Dimension(100, 25));
        OkButton.setMinimumSize(new java.awt.Dimension(100, 25));
        OkButton.setPreferredSize(new java.awt.Dimension(100, 25));
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });
        ChoicesPanel.add(OkButton);

        firstFileLabel.setText("Choisissez votre fichier d'aeroports :");

        secondFileLabel.setText("Choisissez votre fichier de vols :");

        choiceFileButton1.setBackground(new java.awt.Color(235, 173, 59));
        choiceFileButton1.setForeground(new java.awt.Color(0, 0, 0));
        choiceFileButton1.setText("ouvrir");
        choiceFileButton1.setFocusPainted(false);
        choiceFileButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceFileButton1ActionPerformed(evt);
            }
        });

        choiceFileButton2.setBackground(new java.awt.Color(235, 173, 59));
        choiceFileButton2.setForeground(new java.awt.Color(0, 0, 0));
        choiceFileButton2.setText("ouvrir");
        choiceFileButton2.setFocusPainted(false);
        choiceFileButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceFileButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ChoicesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secondFileLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(choiceFileButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstFileLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(choiceFileButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstFileLabel)
                    .addComponent(choiceFileButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondFileLabel)
                    .addComponent(choiceFileButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(ChoicesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        System.out.println("ok");
    }//GEN-LAST:event_OkButtonActionPerformed

    private void choiceFileButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceFileButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceFileButton1ActionPerformed

    private void choiceFileButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceFileButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceFileButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel ChoicesPanel;
    private javax.swing.JButton OkButton;
    private javax.swing.JButton choiceFileButton1;
    private javax.swing.JButton choiceFileButton2;
    private javax.swing.JLabel firstFileLabel;
    private javax.swing.JLabel secondFileLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
