/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sae.View.jFrame;

import javax.swing.JFrame;
import sae.Utils.IconUtil;
import sae.View.jDialog.JInfosDialog;
import sae.View.jDialog.LoadAgraphDialog;

/**
 * Fenêtre de bienvenue de l'application FFRplane. Permet à l'utilisateur de
 * choisir entre différentes options, comme charger un graphe, démarrer
 * l'application ou afficher des informations à propos. Cette fenêtre s'affiche
 * lors du lancement de l'application. Elle contient également un menu Fichier
 * permettant d'ouvrir un graphe. La fenêtre est configurée pour s'adapter à la
 * taille de l'écran de l'utilisateur et utilise une mise en page graphique
 * élaborée.
 *
 * @author fillo
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Instance de la classe IconUtil utilisée pour configurer les icônes des
     * composants graphiques.
     */
    private static final IconUtil iconU = new IconUtil();

    /**
     * Crée une nouvelle instance de WelcomeFrame. (constructeur) Initialise les
     * composants graphiques de la fenêtre, la positionne au centre de l'écran
     * et maximise sa taille.
     */
    public WelcomeFrame() {
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH); this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        /*jButtonLoad.setBackground(new Color(192,192,192,100));
        jButtonStart.setBackground(new Color(192,192,192,100));
        jButtonAbout.setBackground(new Color(192,192,192,100));*/
        iconU.setIcon(this);
        //https://sourceforge.net/p/tus/code/HEAD/tree/tjacobs/ui/swing_ex/JPanelCustomBkground.java
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelChoices = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jOptionsPanel = new javax.swing.JPanel();
        jButtonLoad = new javax.swing.JButton();
        jButtonStart = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();
        jPanelBackground = new javax.swing.JPanel();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemOpenG = new javax.swing.JMenuItem();
        jMenuAffichage = new javax.swing.JMenu();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\fillo\\OneDrive\\Documents\\BUT1_2023-2024\\S2\\BIG SAE\\JAVA\\img\\earthwelcome.gif")); // NOI18N

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FFRplane - Welcome");
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanelChoices.setEnabled(false);
        jPanelChoices.setOpaque(false);
        jPanelChoices.setLayout(new java.awt.GridBagLayout());

        jLabelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 100)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWelcome.setText("FFR’ PLANE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 70, 0);
        jPanelChoices.add(jLabelWelcome, gridBagConstraints);

        jOptionsPanel.setOpaque(false);
        jOptionsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 5));

        jButtonLoad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonLoad.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoad.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\loadIcon.png"));
        jButtonLoad.setText("Charger votre graphe");
        jButtonLoad.setBorder(null);
        jButtonLoad.setContentAreaFilled(false);
        jButtonLoad.setFocusPainted(false);
        jButtonLoad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLoad.setIconTextGap(20);
        jButtonLoad.setPreferredSize(new java.awt.Dimension(145, 180));
        jButtonLoad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonLoad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });
        jOptionsPanel.add(jButtonLoad);

        jButtonStart.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonStart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonStart.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\startIcon.png"));
        jButtonStart.setText("Commencer ?");
        jButtonStart.setBorder(null);
        jButtonStart.setContentAreaFilled(false);
        jButtonStart.setFocusPainted(false);
        jButtonStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonStart.setIconTextGap(10);
        jButtonStart.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonStart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        jOptionsPanel.add(jButtonStart);

        jButtonAbout.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonAbout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAbout.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\aboutIcon.png"));
        jButtonAbout.setText("A propos");
        jButtonAbout.setBorder(null);
        jButtonAbout.setContentAreaFilled(false);
        jButtonAbout.setFocusPainted(false);
        jButtonAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbout.setIconTextGap(10);
        jButtonAbout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });
        jOptionsPanel.add(jButtonAbout);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        jPanelChoices.add(jOptionsPanel, gridBagConstraints);

        getContentPane().add(jPanelChoices);

        jPanelBackground.setOpaque(false);
        jPanelBackground.setLayout(new java.awt.BorderLayout());

        jLabelBackground.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\sae\\Assets\\bg.png"));
        jLabelBackground.setPreferredSize(new java.awt.Dimension(2019, 1080));
        jPanelBackground.add(jLabelBackground, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelBackground);

        jMenuFichier.setText("fichier");

        jMenuItemOpenG.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemOpenG.setText("ouvrir un graphe");
        jMenuItemOpenG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenGActionPerformed(evt);
            }
        });
        jMenuFichier.add(jMenuItemOpenG);

        jMenuBar.add(jMenuFichier);

        jMenuAffichage.setText("affichage");
        jMenuBar.add(jMenuAffichage);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gère les actions déclenchées par les événements associés aux boutons de
     * la fenêtre WelcomeFrame.
     */
    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        MainFrame mainf = new MainFrame();
        mainf.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButtonStartActionPerformed

    /**
     * Affiche une fenêtre modale JInfosDialog lorsque le bouton "À propos" est
     * cliqué. Cette fenêtre fournit des informations sur l'application.
     */
    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
        JInfosDialog infosD = new JInfosDialog(this, true);
        infosD.setLocationRelativeTo(this);
        infosD.setVisible(true);
    }//GEN-LAST:event_jButtonAboutActionPerformed

    /**
     * Affiche une fenêtre modale LoadAgraphDialog lorsque le bouton "Charger"
     * est cliqué. Cette fenêtre permet à l'utilisateur de charger un graphe.
     */
    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        LoadAgraphDialog loadD = new LoadAgraphDialog(this, true);
        loadD.setLocationRelativeTo(this);
        loadD.setVisible(true);
    }//GEN-LAST:event_jButtonLoadActionPerformed

    /**
     * Affiche une fenêtre modale LoadAgraphDialog lorsque l'option "Ouvrir un
     * graphe" du menu est sélectionnée. Cette fenêtre permet à l'utilisateur de
     * charger un graphe.
     */
    private void jMenuItemOpenGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenGActionPerformed
        LoadAgraphDialog loadDialog = new LoadAgraphDialog(this, true);
        loadDialog.setLocationRelativeTo(this);
        loadDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemOpenGActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JMenu jMenuAffichage;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemOpenG;
    private javax.swing.JPanel jOptionsPanel;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelChoices;
    // End of variables declaration//GEN-END:variables
}
